FROM ubuntu:22.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    iproute2 \
    iputils-ping \
    telnet \
    curl \
    openssh-client \
    net-tools \
    traceroute \
    dnsutils \
    && rm -rf /var/lib/apt/lists/*

CMD ["sleep", "infinity"]
